// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://momhxzpozrhyrtrzeyes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vbWh4enBvenJoeXJ0cnpleWVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NjY4NjgsImV4cCI6MjA2ODE0Mjg2OH0.rjLYiLP46A4B7LOwt2hHmjD-GGiqO0Aw-DnMYV48_yY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});